const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"土地类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTudi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"农民管理",
                        "menuJump":"列表",
                        "tableName":"shangjia"
                    }
                ],
                "menu":"农民管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"农民建议管理",
                        "menuJump":"列表",
                        "tableName":"shangjiajianyi"
                    }
                ],
                "menu":"农民建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地管理",
                        "menuJump":"列表",
                        "tableName":"tudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地评价管理",
                        "menuJump":"列表",
                        "tableName":"tudiCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"土地收藏管理",
                        "menuJump":"列表",
                        "tableName":"tudiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"土地订单管理",
                        "menuJump":"列表",
                        "tableName":"tudiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"种植详情管理",
                        "menuJump":"列表",
                        "tableName":"tudiZhongzhi"
                    }
                ],
                "menu":"土地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户建议管理",
                        "menuJump":"列表",
                        "tableName":"yonghujianyi"
                    }
                ],
                "menu":"用户建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"农民建议管理",
                        "menuJump":"列表",
                        "tableName":"shangjiajianyi"
                    }
                ],
                "menu":"农民建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地管理",
                        "menuJump":"列表",
                        "tableName":"tudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"土地评价管理",
                        "menuJump":"列表",
                        "tableName":"tudiCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"土地收藏管理",
                        "menuJump":"列表",
                        "tableName":"tudiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"土地订单管理",
                        "menuJump":"列表",
                        "tableName":"tudiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"种植详情管理",
                        "menuJump":"列表",
                        "tableName":"tudiZhongzhi"
                    }
                ],
                "menu":"土地管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"农民",
        "tableName":"shangjia"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"土地管理",
                        "menuJump":"列表",
                        "tableName":"tudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"土地评价管理",
                        "menuJump":"列表",
                        "tableName":"tudiCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"土地收藏管理",
                        "menuJump":"列表",
                        "tableName":"tudiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"土地订单管理",
                        "menuJump":"列表",
                        "tableName":"tudiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"种植详情管理",
                        "menuJump":"列表",
                        "tableName":"tudiZhongzhi"
                    }
                ],
                "menu":"土地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"用户建议管理",
                        "menuJump":"列表",
                        "tableName":"yonghujianyi"
                    }
                ],
                "menu":"用户建议管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
